from pathlib import Path

ROOT = Path("dist")

PRIVATE_DOCTOR_RULE_HTML = r'''<!DOCTYPE html>
<html lang="ja"><head>
<meta charset="utf-8"/><meta content="width=device-width,initial-scale=1" name="viewport"/>
<meta content="AXIS BAYにおける個人医の開業・治療・事件対応に関する共通ルール" name="description"/><meta content="#061522" name="theme-color"/>
<meta content="website" property="og:type"/><meta content="個人医ルール｜AXIS BAY" property="og:title"/>
<meta content="AXIS BAYにおける個人医の開業・治療・事件対応に関する共通ルール" property="og:description"/>
<title>個人医ルール｜AXIS BAY</title><link href="../assets/css/site.css" rel="stylesheet"/>
</head><body><a class="skip-link" href="#main">本文へ移動</a>
<header class="site-header"><div class="container nav"><a class="brand" href="../index.html"><img alt="AXIS BAY" class="brand-logo" src="https://static.wixstatic.com/media/32c055_d798a13c90e2468c919cc934ce696f19~mv2.png/v1/fill/w_583%2Ch_439%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/icon.png"/><span class="brand-copy"><strong>AXIS BAY</strong><small>ROLEPLAY SERVER</small></span></a><button aria-expanded="false" aria-label="メニュー" class="menu-button" type="button">☰</button><nav class="nav-links"><a href="../index.html">ホーム</a><a href="../about.html">街紹介</a><a aria-current="page" href="../rules.html">ルール</a><a href="../join.html">参加へ</a></nav></div></header>
<main id="main"><section class="page-hero"><div class="container"><div class="breadcrumbs"><a href="../index.html">ホーム</a><span>/</span><a href="../rules.html">ルールセンター</a><span>/</span><span>個人医ルール</span></div><span class="eyebrow">RULES</span><h1>個人医ルール</h1><p class="lead">AXIS BAYにおける個人医の開業・治療・事件対応に関する共通ルール</p><div class="page-meta"><span class="pill">事業・職業</span><span class="pill">ページ内検索</span><span class="pill">10項目</span></div></div></section>
<section class="section-sm"><div class="container"><div class="notice" data-rule-notice=""></div></div></section>
<section class="section rule-detail"><div class="container rule-detail-layout"><aside class="rule-toc"><div class="rule-toc-title">このページの目次</div><a href="#section-1">1．開業方法</a><a href="#section-2">2．弟子制度</a><a href="#section-3">3．治療できる対象者</a><a href="#section-4">4．治療できる場所</a><a href="#section-5">5．服装・車両・請求</a><a href="#section-6">6．事件現場へ向かう際の基本ルール</a><a href="#section-7">7．事件対応時の装備・行動制限</a><a href="#section-8">8．ピックアップ方法</a><a href="#section-9">9．罰則について</a><a href="#section-10">10．禁止事項</a><a class="toc-back" href="../rules.html">← ルール一覧へ</a></aside>
<div class="rule-document"><div class="rule-page-tools"><div><span class="eyebrow">SEARCH THIS RULE</span><h2>個人医ルール</h2><p class="muted">AXIS BAYにおける個人医の開業・治療・事件対応に関する共通ルール</p></div><div class="rule-search-box"><input class="search-input" data-rule-page-search="" placeholder="このルール内を検索" type="search"/><span data-rule-page-count=""></span></div></div><div class="rule-filter-empty" data-rule-filter-empty="" hidden="">一致する項目がありません。</div>
<aside class="rule-callout info"><p><strong>個人医とは：</strong> 犯罪者専属の医師ではありません。指名手配中またはその見込みがある人、銃創患者、犯罪中にダウンした犯罪者など、正規の医療を受けにくい人を、限定された条件で治療する闇医者的な役割です。</p></aside>
<section class="rule-content-section" data-rule-section="" id="section-1"><h2>1．開業方法</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>六法のチケットにて個人医の開業申請の手続きを行います。</span></li><li><span class="rule-marker">●</span><span>申請後に面談を行い、承認された場合は開業許可証が発行されます。</span></li><li><span class="rule-marker">●</span><span>街全体の個人医人数や運営状況によっては、申請が承認されない場合があります。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-2"><h2>2．弟子制度</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>個人医は、弟子を取って育成できます。</span></li><li><span class="rule-marker">●</span><span>弟子を取る場合は、ルール理解・行動・人柄を確認したうえで慎重に判断してください。</span></li><li><span class="rule-marker">●</span><span>弟子がトラブルや問題行為を起こした場合は、弟子だけでなく師匠にも同等の罰則や廃業措置を行う場合があります。</span></li><li><span class="rule-marker">●</span><span>師匠の許可を得て弟子が独立した場合は、その時点で師弟関係を終了します。</span></li></ul><aside class="rule-callout info"><p><strong>連帯責任：</strong> 弟子でいる間の不祥事は師匠にも影響します。弟子へルールを説明し、必要な指導を行ってください。</p></aside></section>
<section class="rule-content-section" data-rule-section="" id="section-3"><h2>3．治療できる対象者</h2><div class="table-scroll"><table class="rule-table"><tr><th><p>項目</p></th><th><p>内容</p></th></tr><tr><td><p>指名手配犯</p></td><td><p>現在指名手配されている人。</p></td></tr><tr><td><p>指名手配の見込みがある人</p></td><td><p>犯罪への関与などにより、今後指名手配される可能性が高い人。</p></td></tr><tr><td><p>銃創患者</p></td><td><p>銃による負傷が確認できる人。</p></td></tr><tr><td><p>事件関係者</p></td><td><p>犯罪・事件に関係して負傷またはダウンした人。</p></td></tr></table></div><aside class="rule-callout warning"><p><strong>治療対象外：</strong> 事故、遊び、日常生活での負傷・ダウンなど、事件性がない患者を個人医が治療することはルール違反です。</p></aside></section>
<section class="rule-content-section" data-rule-section="" id="section-4"><h2>4．治療できる場所</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>個人医の拠点が用意されていますが、街全域で治療できます。ただし、事件性のある患者に限ります。</span></li><li><span class="rule-marker">●</span><span>現場蘇生を行う場合は、一般市民の迷惑にならない安全な場所へ移動してください。</span></li><li><span class="rule-marker">●</span><span>事件性のない蘇生・治療は、場所に関係なく禁止です。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-5"><h2>5．服装・車両・請求</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>服装と車両は自由ですが、黒色は避けてください。</span></li><li><span class="rule-marker">●</span><span>勤務中は、個人医と分かるよう聴診器を着用してください。</span></li><li><span class="rule-marker">●</span><span>個人医は自由診療です。最低料金以上であれば、各自で請求額を設定できます。</span></li><li><span class="rule-marker">●</span><span>医療行為1回ごとに、必ず請求書を発行してください。</span></li><li><span class="rule-marker">●</span><span>最低料金を下回る請求は禁止です。</span></li></ul><h3>個人医の最低料金</h3><div class="table-scroll"><table class="rule-table"><tr><th><p>医療行為</p></th><th><p>最低料金</p></th></tr><tr><td><p>蘇生</p></td><td><p>2,000,000</p></td></tr><tr><td><p>治療</p></td><td><p>1,000,000</p></td></tr></table></div><h3>EMS不在時の病院内料金</h3><div class="table-scroll"><table class="rule-table"><tr><th><p>医療行為</p></th><th><p>料金</p></th></tr><tr><td><p>院内治療（白市民）</p></td><td><p>400,000</p></td></tr><tr><td><p>院内蘇生（白市民）</p></td><td><p>800,000</p></td></tr><tr><td><p>院内治療（犯罪者・黒市民）</p></td><td><p>600,000</p></td></tr><tr><td><p>院内蘇生（犯罪者・黒市民）</p></td><td><p>1,200,000</p></td></tr></table></div><aside class="rule-callout warning"><p><strong>病院内での治療：</strong> EMSが退勤している場合に限り、個人医は病院施設内でEMSと同様の治療を行えます。EMS出勤中の病院敷地内治療は禁止です。</p></aside></section>
<section class="rule-content-section" data-rule-section="" id="section-6"><h2>6．事件現場へ向かう際の基本ルール</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>犯罪が発生した場合、個人医は現場へ向かい、事件関係者の蘇生・治療を行えます。</span></li><li><span class="rule-marker">●</span><span>現場へ向かう際は、必ず無線15番へ参加してください。</span></li><li><span class="rule-marker">●</span><span>現場へ向かえる個人医は2名までです。弟子はこの人数に含みません。</span></li><li><span class="rule-marker">●</span><span>特定のギャングを優遇せず、すべての対象者へ公平に対応してください。</span></li><li><span class="rule-marker">●</span><span>現場では医療行為のみ行ってください。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-7"><h2>7．事件対応時の装備・行動制限</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>銃を所持して事件現場へ向かうことは禁止です。</span></li><li><span class="rule-marker">●</span><span>使用できる装備は、テーザーと鎮静剤のみです。</span></li><li><span class="rule-marker">●</span><span>大型犯罪のNPC戦闘中に警察より先に現場へ入った場合は、鎮静剤を使用できません。テーザーのみ使用できます。</span></li><li><span class="rule-marker">●</span><span>上記の場合でも、治療行為は可能です。</span></li><li><span class="rule-marker">●</span><span>救助目的以外で警察へアタックする行為は禁止です。</span></li><li><span class="rule-marker">●</span><span>現場で個人医が逮捕された場合は、逃走補助罪が適用されます。</span></li><li><span class="rule-marker">●</span><span>警察官を殺害した場合は、公務員殺人（個）が適用されます。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-8"><h2>8．ピックアップ方法</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>通常時は /pickup を使用してください。</span></li><li><span class="rule-marker">●</span><span>バスケットは、歪みなどが発生して通常のピックアップができない緊急時のみ使用できます。</span></li><li><span class="rule-marker">●</span><span>通常時にバスケットを使用することは禁止です。</span></li><li><span class="rule-marker">●</span><span>生存している人をバスケットでピックする行為は禁止です。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-9"><h2>9．罰則について</h2><ul class="rule-source-list"><li><span class="rule-marker">●</span><span>トラブルやルール違反については、関係各所からの聞き取り後、内容により罰則を下します。</span></li><li><span class="rule-marker">●</span><span>罰則は、警告・個人医業の一時停止・新弟子採用の禁止・個人医業のはく奪です。</span></li><li><span class="rule-marker">●</span><span>問題の大きさやトラブルの繰り返し等を考慮して決定いたします。</span></li></ul></section>
<section class="rule-content-section" data-rule-section="" id="section-10"><h2>10．禁止事項</h2><aside class="rule-callout info"><ul class="rule-source-list"><li><span class="rule-marker danger">×</span><span>生存者をバスケットでピックすること。</span></li><li><span class="rule-marker danger">×</span><span>一般市民へ鎮静剤を使用すること。</span></li><li><span class="rule-marker danger">×</span><span>個人医の治療対象ではない患者を治療すること。</span></li><li><span class="rule-marker danger">×</span><span>最低料金を下回る金額で請求すること。</span></li><li><span class="rule-marker danger">×</span><span>EMSが出勤している状態で、病院敷地内の患者を治療すること。</span></li><li><span class="rule-marker danger">×</span><span>銃を所持して事件現場へ向かうこと。</span></li><li><span class="rule-marker danger">×</span><span>救助目的以外で警察へ攻撃・妨害すること。</span></li><li><span class="rule-marker danger">×</span><span>特定のギャングだけを優先・優遇すること。</span></li></ul></aside><aside class="rule-callout warning"><p><strong>運営判断：</strong> 本ルールに記載されていない場合でも、個人医の役割を逸脱する行為、街の公平性を損なう行為、問題行動が確認された場合は、指導・処罰・開業許可の取消し・廃業などの対応を行う場合があります。</p></aside><p>個人医は、犯罪者の味方ではなく、限定条件で医療を提供する中立的な医療役として行動してください。</p></section>
<div class="rule-end-actions"><a class="button button-secondary" href="../rules.html">ルール一覧へ戻る</a><a class="button button-primary" data-config-link="discord" href="#">不明点はチケットへ</a></div>
</div></div></section><section class="section section-alt"><div class="container"><span class="eyebrow">RELATED RULES</span><h2>関連するルール</h2><div class="rule-card-grid"><article class="rule-card" data-rule-card="" data-search-text="犯罪ルール 犯罪開始、人数制限、ROB、禁止行為"><div class="rule-card-top"><span class="rule-card-icon">犯</span><span class="rule-card-group">犯罪・組織</span></div><h3>犯罪ルール</h3><p>犯罪開始、人数制限、ROB、禁止行為</p><a class="card-link" href="../rules/crime.html">全文を見る →</a></article><article class="rule-card" data-rule-card="" data-search-text="救急隊ルール 蘇生、治療、隊員、病院対応"><div class="rule-card-top"><span class="rule-card-icon">救</span><span class="rule-card-group">事業・職業</span></div><h3>救急隊ルール</h3><p>蘇生、治療、隊員、病院対応</p><a class="card-link" href="../rules/ems.html">全文を見る →</a></article><article class="rule-card" data-rule-card="" data-search-text="警察ルール 勤務、装備、事件対応、守秘義務"><div class="rule-card-top"><span class="rule-card-icon">警</span><span class="rule-card-group">事業・職業</span></div><h3>警察ルール</h3><p>勤務、装備、事件対応、守秘義務</p><a class="card-link" href="../rules/police.html">全文を見る →</a></article></div></div></section></main>
<footer class="site-footer"><div class="container footer-row"><div class="footer-brand"><img alt="" src="https://static.wixstatic.com/media/32c055_d798a13c90e2468c919cc934ce696f19~mv2.png/v1/fill/w_583%2Ch_439%2Cal_c%2Cq_85%2Cenc_avif%2Cquality_auto/icon.png"/><span>© <span data-current-year=""></span> AXIS BAY</span></div><div class="footer-links"><a href="../index.html">ホーム</a><a href="../about.html">街紹介</a><a href="../rules.html">ルール</a><a href="../join.html">参加へ</a><a data-config-link="x" href="#">X</a></div></div></footer><script src="../assets/js/config.js"></script><script src="../assets/js/site.js"></script></body></html>'''


def main() -> None:
    path = ROOT / "rules/private-doctor.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(PRIVATE_DOCTOR_RULE_HTML, encoding="utf-8")


if __name__ == "__main__":
    main()
